name: Node.js Test, Build and Notify

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #- run: npm install jest eslint --save-dev
    #- run: npx eslint --init
    #- run: npm run build --if-present
    #- run: npm test
    run: |
          npm install # or yarn install
          npm run lint # or yarn lint
          npm run test # or yarn test
          npm run build # or yarn build
    env:
        CI: true
    
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: test-results/**/*.xml
    
    - name: Run linters
      uses: stefanoeb/eslint-action@1.0.2
      with:
          files: src/
      #with:
      #  github_token: ${{ secrets.GITHUB_TOKEN }}
        # Enable linters
       # eslint: true
       # prettier: false
        
   # - name: Publish Docker
   #   if: success()
   #   uses: elgohr/Publish-Docker-Github-Action@2.11
   #   with:
   #     # The name of the image you would like to push
   #     name: 9841463058/nodejs_githubactions
   #     # The login username for the registry
   #     username: ${{ secrets.DOCKERHUB_USER }}
        # The login password for the registry
    #    password: ${{ secrets.DOCKERHUB_PASS }}

  
   # - name: GitHub Action for Slack
   #   if: success()
   #   env:
   #    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
   #   uses: Ilshidur/action-slack@1.6.2
   #   with:
   #    args: 'A new version of your Node.js app has been built'
